name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: python-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: pylint check script
        run: |
          pip install pylint,
          echo test, and deploy your project.
